### ISSUE TITLE
Can not load token from env

### ISSUE THREAD

**Issue by mazgi** [mazgi/fluent-plugin-slackrtm#1]
```shellsession
$ < etc/fluentd/slack-logs.conf
<source>
  @type slackrtm
  token "#{ENV['SLACK_TOKEN']}"
  tag slack
</source>

<match **>
  @type stdout
</match>
$ < .env
SLACK_TOKEN='********'
```

<details>
<summary>

```shellsession
2017-06-11 18:56:30 +0900 [info]: fluent/engine.rb:133:configure: using configuration file: <ROOT>
  <source>
    @type slackrtm
    token xxxxxx
    tag slack
  </source>
  <match **>
    @type stdout
  </match>
</ROOT>
2017-06-11 18:56:31 +0900 [error]: fluent/engine.rb:208:rescue in run: unexpected error error_class=ArgumentError error=#<ArgumentError: bad argument (expected URI object or URI string)>
  2017-06-11 18:56:31 +0900 [error]: fluent/supervisor.rb:162:block in start: /Users/hidenori.matsuki/.rbenv/versions/2.4.1/lib/ruby/2.4.0/uri/common.rb:739:in `URI'
  2017-06-11 18:56:31 +0900 [error]: fluent/supervisor.rb:162:block in start: /Users/hidenori.matsuki/Creations/mazgi/slack2bq/vendor/bundle/ruby/2.4.0/gems/slack-rtmapi-1.0.0.rc4/lib/slack-rtmapi.rb:17:in `get_url'
  2017-06-11 18:56:31 +0900 [error]: fluent/supervisor.rb:162:block in start: /Users/hidenori.matsuki/Creations/mazgi/slack2bq/vendor/bundle/ruby/2.4.0/gems/fluent-plugin-slackrtm-0.2.4/lib/fluent/plugin/in_slackrtm.rb:14:in `block in start'
2017-06-11 18:56:31 +0900 [info]: fluent/engine.rb:211:run: shutting down fluentd
```
</summary>

```shellsession
$ env $(cat .env) bundle exec fluentd --config etc/fluentd/slack-logs.conf -vv
2017-06-11 18:56:30 +0900 [info]: fluent/supervisor.rb:471:read_config: reading config file path="etc/fluentd/slack-logs.conf"
2017-06-11 18:56:30 +0900 [info]: fluent/supervisor.rb:337:supervise: starting fluentd-0.12.36
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered buffer plugin 'file'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered buffer plugin 'memory'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered filter plugin 'grep'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered filter plugin 'parser'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered filter plugin 'record_transformer'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered filter plugin 'stdout'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered input plugin 'debug_agent'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered input plugin 'dummy'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered input plugin 'exec'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered input plugin 'forward'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered input plugin 'gc_stat'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered input plugin 'http'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered input plugin 'monitor_agent'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered input plugin 'object_space'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered input plugin 'status'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered input plugin 'unix'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered input plugin 'syslog'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered input plugin 'tail'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered input plugin 'tcp'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered input plugin 'udp'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered output plugin 'copy'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered output plugin 'exec'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered output plugin 'exec_filter'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered output plugin 'file'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered output plugin 'forward'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered output plugin 'null'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered output plugin 'relabel'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered output plugin 'roundrobin'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered output plugin 'stdout'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered output plugin 'tcp'
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered output plugin 'unix'
2017-06-11 18:56:30 +0900 [info]: fluent/engine.rb:126:block in configure: gem 'fluentd' version '0.12.36'
2017-06-11 18:56:30 +0900 [info]: fluent/engine.rb:126:block in configure: gem 'fluent-mixin-config-placeholders' version '0.4.0'
2017-06-11 18:56:30 +0900 [info]: fluent/engine.rb:126:block in configure: gem 'fluent-plugin-slackrtm' version '0.2.4'
2017-06-11 18:56:30 +0900 [info]: fluent/agent.rb:129:add_match: adding match pattern="**" type="stdout"
2017-06-11 18:56:30 +0900 [info]: fluent/root_agent.rb:152:add_source: adding source type="slackrtm"
2017-06-11 18:56:30 +0900 [trace]: fluent/plugin.rb:122:register_impl: registered input plugin 'slackrtm'
2017-06-11 18:56:30 +0900 [info]: fluent/engine.rb:133:configure: using configuration file: <ROOT>
  <source>
    @type slackrtm
    token xxxxxx
    tag slack
  </source>
  <match **>
    @type stdout
  </match>
</ROOT>
2017-06-11 18:56:31 +0900 [error]: fluent/engine.rb:208:rescue in run: unexpected error error_class=ArgumentError error=#<ArgumentError: bad argument (expected URI object or URI string)>
  2017-06-11 18:56:31 +0900 [error]: fluent/supervisor.rb:162:block in start: /Users/hidenori.matsuki/.rbenv/versions/2.4.1/lib/ruby/2.4.0/uri/common.rb:739:in `URI'
  2017-06-11 18:56:31 +0900 [error]: fluent/supervisor.rb:162:block in start: /Users/hidenori.matsuki/Creations/mazgi/slack2bq/vendor/bundle/ruby/2.4.0/gems/slack-rtmapi-1.0.0.rc4/lib/slack-rtmapi.rb:17:in `get_url'
  2017-06-11 18:56:31 +0900 [error]: fluent/supervisor.rb:162:block in start: /Users/hidenori.matsuki/Creations/mazgi/slack2bq/vendor/bundle/ruby/2.4.0/gems/fluent-plugin-slackrtm-0.2.4/lib/fluent/plugin/in_slackrtm.rb:14:in `block in start'
2017-06-11 18:56:31 +0900 [info]: fluent/engine.rb:211:run: shutting down fluentd
2017-06-11 18:56:31 +0900 [info]: fluent/root_agent.rb:125:block (2 levels) in shutdown: shutting down input type="slackrtm" plugin_id="object:3fc029ad9fac"
2017-06-11 18:56:31 +0900 [info]: fluent/agent.rb:99:block (2 levels) in shutdown: shutting down output type="stdout" plugin_id="object:3fc029a15918"
2017-06-11 18:56:31 +0900 [info]: fluent/supervisor.rb:354:supervise: process finished code=0
2017-06-11 18:56:31 +0900 [warn]: fluent/supervisor.rb:357:supervise: process died within 1 second. exit.
```
</details>

**Comment by mazgi** [comment]
It's my mistake

```shellsession
$ export SLACK_TOKEN='********'
$ bundle exec fluentd --config etc/fluentd/slack-logs.conf --use-v1-config -v
2017-06-11 20:07:26 +0900 [info]: fluent/supervisor.rb:471:read_config: reading config file path="etc/fluentd/slack-logs.conf"
2017-06-11 20:07:26 +0900 [info]: fluent/supervisor.rb:337:supervise: starting fluentd-0.12.36
2017-06-11 20:07:27 +0900 [info]: fluent/engine.rb:126:block in configure: gem 'fluentd' version '0.12.36'
2017-06-11 20:07:27 +0900 [info]: fluent/engine.rb:126:block in configure: gem 'fluent-mixin-config-placeholders' version '0.4.0'
2017-06-11 20:07:27 +0900 [info]: fluent/engine.rb:126:block in configure: gem 'fluent-plugin-slackrtm' version '0.2.4'
2017-06-11 20:07:27 +0900 [info]: fluent/agent.rb:141:add_filter: adding filter in @SLACKRTM_RAW pattern="**" type="grep"
2017-06-11 20:07:27 +0900 [info]: fluent/agent.rb:129:add_match: adding match in @SLACKRTM_RAW pattern="**" type="copy"
2017-06-11 20:07:27 +0900 [debug]: plugin/out_copy.rb:44:block in configure: adding store type="relabel"
2017-06-11 20:07:27 +0900 [info]: fluent/agent.rb:129:add_match: adding match in @SLACKRTM_MESSAGE pattern="**" type="stdout"
2017-06-11 20:07:27 +0900 [info]: fluent/root_agent.rb:152:add_source: adding source type="slackrtm"
2017-06-11 20:07:27 +0900 [info]: fluent/engine.rb:133:configure: using configuration file: <ROOT>
  <source>
    @type slackrtm
    token xxxxxx
    tag mazgi.slack.com
    @label @SLACKRTM_RAW
  </source>
  <label @SLACKRTM_RAW>
    <filter>
      @type grep
      regexp1 type message
    </filter>
    <match **>
      @type copy
      <store>
        @type relabel
        @label @SLACKRTM_MESSAGE
      </store>
    </match>
  </label>
  <label @SLACKRTM_MESSAGE>
    <match **>
      @type stdout
    </match>
  </label>
</ROOT>
^C2017-06-11 20:07:28 +0900 [debug]: fluent/supervisor.rb:529:block in install_main_process_signal_handlers: fluentd main process get SIGINT
2017-06-11 20:07:28 +0900 [debug]: fluent/supervisor.rb:392:block in install_supervisor_signal_handlers: fluentd supervisor process get SIGINT
2017-06-11 20:07:28 +0900 [debug]: fluent/supervisor.rb:532:block in install_main_process_signal_handlers: getting start to shutdown main process
2017-06-11 20:07:28 +0900 [debug]: fluent/supervisor.rb:529:block in install_main_process_signal_handlers: fluentd main process get SIGINT
2017-06-11 20:07:28 +0900 [info]: fluent/engine.rb:211:run: shutting down fluentd
2017-06-11 20:07:28 +0900 [info]: fluent/root_agent.rb:125:block (2 levels) in shutdown: shutting down input type="slackrtm" plugin_id="object:3fd169d24234"
2017-06-11 20:07:28 +0900 [info]: fluent/agent.rb:85:block (2 levels) in shutdown: shutting down filter in @SLACKRTM_RAW type="grep" plugin_id="object:3fd168d46768"
2017-06-11 20:07:28 +0900 [info]: fluent/agent.rb:99:block (2 levels) in shutdown: shutting down output in @SLACKRTM_RAW type="copy" plugin_id="object:3fd168d4ae30"
2017-06-11 20:07:28 +0900 [info]: fluent/agent.rb:99:block (2 levels) in shutdown: shutting down output in @SLACKRTM_MESSAGE type="stdout" plugin_id="object:3fd168d4ecc4"
2017-06-11 20:07:28 +0900 [info]: fluent/supervisor.rb:354:supervise: process finished code=0
```
